<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio Version=3.0.71.10?>
<Program xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File Description="Local data types" Private="true">bnrmain.typ</File>
    <File Description="Local variables" Private="true">bnrmain.var</File>
    <File Description="Implementation code">bnrmain.c</File>
    <File>bnradmin.c</File>
    <File>bnrkp.c</File>
    <File>bnraninput.c</File>
    <File>bnrauto.c</File>
    <File>bnrchains.c</File>
    <File>bnrcomputer.c</File>
    <File>bnrcomserver.c</File>
    <File>bnrconfig.c</File>
    <File>bnrcyclicsystem.c</File>
    <File>bnrdebug.c</File>
    <File>bnrdigsensor.c</File>
    <File>bnrdirmodule.c</File>
    <File>bnrflash.c</File>
    <File>bnrhardpin.c</File>
    <File>bnrhconfig.c</File>
    <File>bnridlesensor.c</File>
    <File>bnringate.c</File>
    <File>single.c</File>
    <File>bnrmodule101.c</File>
    <File>bnrmysystem.c</File>
    <File>bnrmytimer.c</File>
    <File>bnrobserve.c</File>
    <File>bnroutgate.c</File>
    <File>bnrpin.c</File>
    <File>bnrpob.c</File>
    <File>bnrprocmanager.c</File>
    <File>bnrregedit.c</File>
    <File>bnrsensr.c</File>
    <File>bnrslide.c</File>
    <File>bnrsmartsensor.c</File>
    <File>bnrsystemtimer.c</File>
    <File>bnrtelecontrol.c</File>
    <File>bnrteleind.c</File>
    <File>bnrtelesensor.c</File>
    <File>bnrtelesignal.c</File>
    <File>multi.c</File>
    <File>bnradmin.h</File>
    <File>bnraninput.h</File>
    <File>bnrauto.h</File>
    <File>bnrcomputer.h</File>
    <File>bnrcomserver.h</File>
    <File>bnrconst.h</File>
    <File>bnrcyclicsystem.h</File>
    <File>bnrdbout.h</File>
    <File>bnrdebug.h</File>
    <File>bnrdigsensor.h</File>
    <File>bnrdirmodule.h</File>
    <File>bnrflash.h</File>
    <File>bnrhardpin.h</File>
    <File>bnrhconfig.h</File>
    <File>bnridlesensor.h</File>
    <File>bnringate.h</File>
    <File>bnrkp.h</File>
    <File>bnrmain.h</File>
    <File>bnrmessage.h</File>
    <File>bnrmodule101.h</File>
    <File>bnrmysystem.h</File>
    <File>bnrmytimer.h</File>
    <File>bnrobserve.h</File>
    <File>bnroutgate.h</File>
    <File>bnrpin.h</File>
    <File>bnrpob.h</File>
    <File>bnrprocmanager.h</File>
    <File>bnrregedit.h</File>
    <File>bnrsensr.h</File>
    <File>bnrslide.h</File>
    <File>bnrsmartsensor.h</File>
    <File>bnrsystemtimer.h</File>
    <File>bnrtelecontrol.h</File>
    <File>bnrteleind.h</File>
    <File>bnrtelesensor.h</File>
    <File>bnrtelesignal.h</File>
    <File>multi.h</File>
    <File>single.h</File>
    <File>typedefs.h</File>
    <File>bnrcomvs1.h</File>
    <File>bnrcomvs0.c</File>
    <File>bnrcomvs0.h</File>
    <File>bnrcomvs1.c</File>
    <File>bnrdevtu.h</File>
    <File>bnrdevts.c</File>
    <File>bnrdevts.h</File>
    <File>bnrdevtu.c</File>
    <File>bnrdvs.h</File>
    <File>bnrdvs.c</File>
    <File>bnrfreq.h</File>
    <File>bnrfreq.c</File>
    <File>bnrlevel.h</File>
    <File>bnrlevel.c</File>
    <File>bnrmeasur.h</File>
    <File>bnrmeasur.c</File>
    <File>bnrobsys.h</File>
    <File>bnrobsys.c</File>
    <File>bnrpress.h</File>
    <File>bnrpress.c</File>
    <File>bnrpunit.h</File>
    <File>bnrpunit.c</File>
    <File>bnrstgate.h</File>
    <File>bnrstgate.c</File>
    <File>bnrtcpserver.h</File>
    <File>bnrtcpserver.c</File>
    <File>bnrtu.h</File>
    <File>bnrtemper.c</File>
    <File>bnrtemper.h</File>
    <File>bnrts.c</File>
    <File>bnrts.h</File>
    <File>bnrtu.c</File>
    <File>bnrdevice.h</File>
    <File>bnrdevice.c</File>
    <File>bnrcount.h</File>
    <File>bnrcount.c</File>
  </Files>
</Program>